#!/bin/bash
# How to do argument parsing in bash : https://stackoverflow.com/questions/192249/how-do-i-parse-command-line-arguments-in-bash
echo "Labelling semantics for each posts"
cd ../..
python3.6 -m analysis._3_label_semantic.main $@
echo "DONE."