#!/bin/bash
source activate my_env # Launch into Anaconda session, because some libraries are only available in Anaconda

echo "Output is redirected to ./analysis_log, so you won't see any output here."
# Redirect STDOUT to analysis_log
exec > ./analysis_log

START_TIME=`date +%s`

# Run test
./test

# If some test fail , exit with error
if [ $? -ne 0 ]; then
    exit 1
fi

cd './_1_process_raw_data'
./run $@
cd ..

cd './_2_remove_unrelated_data'
./run $@
cd ..

cd './_3_label_semantic'
./run $@
cd ..

cd './_4_classification'
./run $@
cd ..

python './check_correctness.py'

END_TIME=`date +%s`
MINUTES_TOOK=$((($END_TIME - $START_TIME)/60))
SECONDS_TOOK=$((($END_TIME - $START_TIME)%60))

echo "The analysis process started at : $(date -d @$START_TIME)"
echo "The analysis process ended at   : $(date -d @$END_TIME)"
echo "The analysis process took $MINUTES_TOOK minutes $SECONDS_TOOK seconds. "

