#!/bin/bash
function check_error {
    if [ $? -ne 0 ]; then
        printf "Please fix this failing test first at $1"
        exit 1
    fi
}

function run_test_at {
    cd $1
    for file in `ls test*`
    do
        pytest -vv $file
        check_error "\n$1/$file"
    done
    cd ..
}

run_test_at './tests'
run_test_at './_1_process_raw_data/tests'
run_test_at './_2_remove_unrelated_data/tests'
run_test_at './_3_label_semantic/tests'
run_test_at './_4_classification/tests'
